'use client';

import { Story } from '@/lib/api';
import { Globe, FileText } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';

interface StoryCardProps {
  story: Story;
  rank: number;
}

export function StoryCard({ story, rank }: StoryCardProps) {
  let timeAgo = '';
  try {
    timeAgo = formatDistanceToNow(new Date(story.time * 1000), { addSuffix: true });
  } catch (e) {
    timeAgo = 'recently';
  }

  let domain = '';
  if (story.url) {
    try {
      domain = new URL(story.url).hostname.replace(/^www\./, '');
    } catch (e) {
      domain = 'web';
    }
  }

  const commentText = story.descendants === 1 ? '1 comment' : `${story.descendants || 0} comments`;
  const hnUrl = `https://news.ycombinator.com/item?id=${story.id}`;

  return (
    <article className="h-screen w-full snap-start relative flex flex-col justify-center items-center p-6 md:p-8 bg-gradient-to-b from-gray-900 via-gray-900 to-black text-white overflow-hidden select-none">
      
      {/* Title Area */}
      <div className="z-10 flex flex-col items-center gap-6 max-w-5xl w-full text-center -mt-20">
        
        {/* Rank Indicator */}
        <div className="text-lg md:text-xl font-medium text-white/50 tracking-widest font-mono">
            #{rank}
        </div>

        <h1 className="text-4xl md:text-6xl lg:text-7xl font-extrabold leading-tight tracking-tight drop-shadow-2xl">
          {story.url ? (
            <a href={story.url} target="_blank" rel="noopener noreferrer" className="hover:text-gray-300 transition-colors">
              {story.title}
            </a>
          ) : (
            story.title
          )}
        </h1>
        
        <div className="flex flex-col items-center gap-4">
            {domain && (
                <a 
                  href={story.url} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-gray-400 text-sm md:text-base font-medium px-3 py-1 rounded-full bg-white/5 border border-white/5 backdrop-blur-sm hover:bg-white/10 transition-colors"
                >
                    <Globe size={14} />
                    <span>{domain}</span>
                </a>
            )}

            {/* Simple HN-style metadata linking to HN */}
            <a 
              href={hnUrl} 
              target="_blank" 
              rel="noopener noreferrer"
              className="group flex items-center gap-2 text-white/40 text-xs md:text-sm font-normal tracking-wide hover:text-white/60 transition-colors py-1 rounded-full"
            >
                <div>
                    <span>{story.score} points</span>
                    <span className="mx-1 opacity-50">by</span>
                    <span className="font-medium text-white/60">{story.by}</span>
                    <span className="mx-1.5 opacity-30">|</span>
                    <span>{timeAgo}</span>
                    <span className="mx-1.5 opacity-30">|</span>
                    <span className="font-medium text-white/60">{commentText}</span>
                </div>
            </a>
        </div>
      </div>

      {/* AI Summary Block (Bottom-Center) */}
      <div className="absolute bottom-10 left-1/2 -translate-x-1/2 w-full max-w-xl px-4 hidden lg:block z-10">
        <div className="bg-black/30 backdrop-blur-xl border border-white/10 rounded-2xl p-4 md:p-5 shadow-xl transition-all hover:bg-black/40">
           <div className="flex gap-3">
             <div className="min-w-[24px] pt-1 text-purple-400">
                <FileText size={20} />
             </div>
             <div>
                <h3 className="text-xs font-bold text-purple-300 uppercase tracking-wider mb-1">AI Summary</h3>
                <p className="text-sm text-gray-300 leading-relaxed">
                  This feature is a placeholder. In a full production build, this area would contain a concise summary of the article content generated by an LLM.
                </p>
             </div>
           </div>
        </div>
      </div>
    </article>
  );
}
